"""Three-layer prompt assembly for state machine workflows.

Assembles prompts from:
1. Global prompt — loaded from a .md file referenced in config
2. Stage prompt — loaded from the state's prompt .md file
3. Lifecycle injection — auto-generated from config + Linear data
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from jinja2 import BaseLoader, Environment, Undefined

from .config import LinearStatesConfig, ServiceConfig, StateConfig
from .models import Issue
from .tracking import get_comments_since, get_last_tracking_timestamp

log = logging.getLogger(__name__)


def load_prompt_file(path: str, workflow_dir: str | Path) -> str:
    """Load a .md prompt file relative to the workflow directory.

    Args:
        path: File path (absolute or relative to workflow_dir).
        workflow_dir: Directory containing the workflow file.

    Returns:
        The file contents as a string.

    Raises:
        FileNotFoundError: If the resolved path does not exist.
    """
    p = Path(path)
    if not p.is_absolute():
        p = Path(workflow_dir) / p
    p = p.resolve()
    if not p.exists():
        raise FileNotFoundError(f"Prompt file not found: {p}")
    return p.read_text()


def render_template(template_str: str, context: dict[str, Any]) -> str:
    """Render a Jinja2 template string with the given context.

    Uses a permissive undefined handler so missing variables render as
    empty strings rather than raising errors.
    """
    env = Environment(loader=BaseLoader(), undefined=_SilentUndefined)
    template = env.from_string(template_str)
    return template.render(**context)


class _SilentUndefined(Undefined):
    """Jinja2 undefined that renders as empty string instead of raising."""

    def __str__(self) -> str:
        return ""

    def __iter__(self) -> Any:
        return iter([])

    def __bool__(self) -> bool:
        return False

    def _fail_with_undefined_error(self, *args: Any, **kwargs: Any) -> Any:
        return _SilentUndefined()

    def __getattr__(self, name: str) -> _SilentUndefined:
        if name.startswith("_"):
            raise AttributeError(name)
        return _SilentUndefined()

    def __getitem__(self, name: str) -> _SilentUndefined:
        return _SilentUndefined()


def build_template_context(
    issue: Issue,
    state_name: str,
    run: int = 1,
    attempt: int = 1,
    last_run_at: str | None = None,
) -> dict[str, Any]:
    """Build the Jinja2 template context dict from issue and run metadata.

    Args:
        issue: The Linear issue being worked on.
        state_name: Internal state machine state name.
        run: Current run number for this state.
        attempt: Retry attempt within this run.
        last_run_at: ISO timestamp of the last run, if any.

    Returns:
        A flat dict suitable for Jinja2 rendering.
    """
    return {
        "issue_id": issue.id,
        "issue_identifier": issue.identifier,
        "issue_title": issue.title,
        "issue_description": issue.description or "",
        "issue_url": issue.url or "",
        "issue_priority": issue.priority,
        "issue_state": issue.state,
        "issue_branch": issue.branch_name or "",
        "issue_labels": issue.labels,
        "state_name": state_name,
        "run": run,
        "attempt": attempt,
        "last_run_at": last_run_at or "",
    }


def build_lifecycle_section(
    issue: Issue,
    state_name: str,
    state_cfg: StateConfig,
    linear_states: LinearStatesConfig,
    run: int = 1,
    is_rework: bool = False,
    recent_comments: list[dict[str, Any]] | None = None,
) -> str:
    """Generate the auto-injected lifecycle section.

    This section is appended to every prompt to give the agent context about
    the current issue, state, and what actions to take when done.

    Args:
        issue: The Linear issue.
        state_name: Internal state machine state name.
        state_cfg: Configuration for the current state.
        linear_states: Linear state name mappings.
        run: Current run number.
        is_rework: Whether this is a rework run after gate rejection.
        recent_comments: Non-tracking comments since last run.

    Returns:
        A markdown string clearly demarcated as auto-generated.
    """
    lines: list[str] = []

    lines.append("---")
    lines.append("<!-- AUTO-GENERATED BY STOKOWSKI — DO NOT EDIT -->")
    lines.append("")
    lines.append("## Lifecycle Context")
    lines.append("")
    lines.append(f"- **Issue:** {issue.identifier} — {issue.title}")
    if issue.url:
        lines.append(f"- **URL:** {issue.url}")
    lines.append(f"- **State:** {state_name}")
    lines.append(f"- **Run:** {run}")
    lines.append("")

    # Rework information
    if is_rework:
        lines.append("### Rework")
        lines.append("")
        lines.append(
            "This is a **rework run**. A previous submission was reviewed "
            "and sent back for changes."
        )
        lines.append("")
        if recent_comments:
            lines.append("**Review comments:**")
            lines.append("")
            for comment in recent_comments:
                body = comment.get("body", "").strip()
                created = comment.get("createdAt", "")
                if body:
                    lines.append(f"> {body}")
                    if created:
                        lines.append(f"> — {created}")
                    lines.append("")
        lines.append(
            "Address the feedback above before resubmitting."
        )
        lines.append("")

    # Recent activity (non-rework)
    if not is_rework and recent_comments:
        lines.append("### Recent Activity")
        lines.append("")
        for comment in recent_comments:
            body = comment.get("body", "").strip()
            created = comment.get("createdAt", "")
            if body:
                lines.append(f"> {body}")
                if created:
                    lines.append(f"> — {created}")
                lines.append("")

    # Available transitions
    if state_cfg.transitions:
        lines.append("### Transitions")
        lines.append("")
        for trigger, target in state_cfg.transitions.items():
            lines.append(f"- `{trigger}` → **{target}**")
        lines.append("")

    # Evidence + reporting contract. Stokowski, not the agent, writes the
    # Linear comment — a model asked to summarise its own work will reliably
    # produce something readable and unreliably produce something checkable.
    lines.extend(build_reporting_contract())

    lines.append("<!-- END STOKOWSKI LIFECYCLE -->")

    return "\n".join(lines)


# Written into every prompt. The report is a file rather than a section of the
# final message so it survives truncation and cannot blur into prose.
REPORT_SCHEMA = """{
  "classification": "bug-fix | improvement | prototype | investigation | chore | docs",
  "confidence": "high | medium | low",
  "headline": "one sentence, the single most important thing you found or did",
  "summary": "markdown prose; the argument, not a list of activities",
  "data_sources": [
    {"name": "what you read from, e.g. production read replica",
     "how_verified": "how you PROVED it was that source and not another"}
  ],
  "claims": [
    {"claim": "a specific factual assertion",
     "evidence": "the observation that supports it, with numbers where they exist",
     "source": "file:line, query, command, or URL a reader can check",
     "confidence": "high | medium | low"}
  ],
  "changes": [{"file": "path", "what": "what changed and why"}],
  "verification": [
    {"check": "the exact command run", "result": "pass | fail | skip", "detail": "output summary"}
  ],
  "artifacts": [{"file": "exact filename you wrote", "caption": "what it shows"}],
  "assumptions": ["decisions you made without being told, and why"],
  "risks": ["what could go wrong with this work"],
  "open_questions": ["what you could not resolve"],
  "next": "what should happen next"
}"""


def build_reporting_contract() -> list[str]:
    """The evidence + report requirements appended to every agent prompt."""
    lines: list[str] = []

    lines.append("### Evidence")
    lines.append("")
    lines.append(
        "Write any screenshots, recordings or exported data into "
        "`$STOKOWSKI_ARTIFACTS` (also at `.stokowski/artifacts/` in this "
        "workspace). Stokowski uploads whatever is in there to the Linear "
        "issue and then deletes it."
    )
    lines.append("")
    lines.append(
        "Do NOT write evidence anywhere else in the repository. Files left "
        "outside that directory are not collected, are never seen by a human, "
        "and risk being committed."
    )
    lines.append("")
    lines.append(
        "If your work changes anything a person can see, capture it. A "
        "before/after pair is worth more than a paragraph describing one."
    )
    lines.append("")

    lines.append("### When Done")
    lines.append("")
    lines.append(
        "Write `.stokowski/report.json` in the workspace root. Stokowski reads "
        "it and posts the Linear comment for you — do NOT post a summary "
        "comment on the issue yourself, it will be duplicated."
    )
    lines.append("")
    lines.append("```json")
    lines.append(REPORT_SCHEMA)
    lines.append("```")
    lines.append("")
    lines.append(
        "Rules for the report, in order of how often they are broken:"
    )
    lines.append("")
    lines.append(
        "1. **Every claim needs a source a human can independently check.** "
        "A claim with an empty `evidence` or `source` is published with a "
        "warning marker beside it, so an unsupported assertion is worse than "
        "an omitted one."
    )
    lines.append(
        "2. **Name the data source and prove it.** State which database, "
        "environment, branch or file you actually read, and how you confirmed "
        "it was that one. Reading the wrong environment and reasoning "
        "perfectly from it is the most common way this work fails."
    )
    lines.append(
        "3. **Report the exact verification commands you ran and their real "
        "results.** Do not write `pass` for a check you did not run."
    )
    lines.append(
        "4. **Record what you assumed.** Anything you decided without being "
        "told belongs in `assumptions`, however obvious it felt."
    )
    lines.append(
        "5. **Lower your confidence when you are guessing.** `low` on a real "
        "finding is more useful than `high` on a shaky one."
    )
    lines.append("")

    return lines

def assemble_prompt(
    cfg: ServiceConfig,
    workflow_dir: str | Path,
    issue: Issue,
    state_name: str,
    state_cfg: StateConfig,
    run: int = 1,
    is_rework: bool = False,
    attempt: int = 1,
    last_run_at: str | None = None,
    comments: list[dict[str, Any]] | None = None,
) -> str:
    """Orchestrate three-layer prompt assembly.

    Combines:
    1. Global prompt (from config's prompts.global_prompt path)
    2. Stage prompt (from state_cfg.prompt path)
    3. Lifecycle injection (auto-generated)

    Each layer is rendered as a Jinja2 template with the issue context.

    Args:
        cfg: The full service config.
        workflow_dir: Directory containing the workflow file.
        issue: The Linear issue.
        state_name: Internal state machine state name.
        state_cfg: Configuration for the current state.
        run: Current run number.
        is_rework: Whether this is a rework run.
        attempt: Retry attempt within this run.
        last_run_at: ISO timestamp of the last run.
        comments: All comments on the issue (for filtering).

    Returns:
        The fully assembled prompt string.
    """
    context = build_template_context(
        issue=issue,
        state_name=state_name,
        run=run,
        attempt=attempt,
        last_run_at=last_run_at,
    )

    parts: list[str] = []

    # Layer 1: Global prompt
    if cfg.prompts.global_prompt:
        try:
            raw = load_prompt_file(cfg.prompts.global_prompt, workflow_dir)
            rendered = render_template(raw, context)
            parts.append(rendered)
        except FileNotFoundError:
            log.warning(
                "Global prompt file not found: %s", cfg.prompts.global_prompt
            )

    # Layer 2: Stage prompt
    if state_cfg.prompt:
        try:
            raw = load_prompt_file(state_cfg.prompt, workflow_dir)
            rendered = render_template(raw, context)
            parts.append(rendered)
        except FileNotFoundError:
            log.warning(
                "Stage prompt file not found for state '%s': %s",
                state_name,
                state_cfg.prompt,
            )

    # Layer 3: Lifecycle injection
    # Filter comments to recent non-tracking ones
    recent: list[dict[str, Any]] = []
    if comments:
        last_ts = get_last_tracking_timestamp(comments)
        recent = get_comments_since(comments, last_ts)

    lifecycle = build_lifecycle_section(
        issue=issue,
        state_name=state_name,
        state_cfg=state_cfg,
        linear_states=cfg.linear_states,
        run=run,
        is_rework=is_rework,
        recent_comments=recent,
    )
    parts.append(lifecycle)

    return "\n\n".join(parts)
